name: Build and Publish
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build
        run: dotnet build --configuration Release ./NumbersToWords/NumbersToWords.csproj
      - name: Test
        run: dotnet test ./NumbersToWords.Test/NumbersToWords.Test.csproj
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Publish to nuget
        uses: rohith/publish-nuget@v1
        with:
          project_dir: NumbersToWords
          nuget_key: ${{ secrets.NUGET_API_KEY }}
