name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build with dotnet
        run: dotnet build --configuration Release NumbersToWords/NumbersToWords.csproj
      - name: Test
        run: dotnet test NumbersToWords.Test/NumbersToWords.Test.csproj
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Pack
        run: dotnet pack NumbersToWords/NumbersToWords.csproj
